@echo off 
cls 
color 0E 
echo ***************************************
echo     COPYRIGHT by badboy 2009
echo ***************************************
echo. & pause
echo 正在清除系统垃圾文件，请稍等......
　　del  /s /q *.iex
　　del  /s /q *.__i
　　del  /s /q *._i
　　del  /s /q *.i
　　del  /s /q *.Administrator
　　del  /s /q *.lst
　　del  /s /q *.obj
　　del  /s /q *.log
      del  /s /q  *.lnp
      del  /s /q  *.Bak
      del  /s /q  *.LST
      del  /s /q  *.OBJ
      del  /s /q  *.M51
      del  /s /q  *.Opt             Rem  文件默认打开
      del  /s /q  *.plg
      del  /s /q  *.Dat
      del  /s /q  *.crf
      del  /s /q  *.d
      del  /s /q  *.o
      del  /s /q  *.axf             Rem  文件默认打开
      del  /s /q  *.fed
      del  /s /q  *.tra
      del  /s /q  *.sct
      del  /s /q  *.map

color 0A 
echo ***************************************
echo 清除系统垃圾完成!!!
echo COPYRIGHT by badboy  2009
echo ***************************************
;echo. & pause

